# Cherokee #

country = { 
    tag = CHE 
    colonialattempts = 0 
    colonialnation = no 
    major = no 
    colonists = 0 
    cancelledloans = 0 
    extendedloans = 0 
    treasury = 99 
    inflation = 0 
    merchants = 0.083333 
    religion = { type = gorgetism }
    culture = { type = cherokee }
    diplomacy = { 
    } 
    knownprovinces = { 
      	48 52 53 54 55 56 60 61 62 63 65 66 67 69 70 71 72 81 82 83 84 85 86 87 88 89 90 91 92 97 98 100 1369 1370 1371 1372 }
    ownedprovinces = { 
        55 61 } 
    controlledprovinces = { 
        55 61 } 
    nationalprovinces = { 
        55 56 61 }  
    city = {
    	fortress = { level = 1 }  
        population = 2000
        location = 55 
        capital = yes 
        } 
    city = {
        population = 1000
        location = 61 
        } 
    technology = {
		stability = { level = 2 value = 42 }
        infra = { level = 0 value = 20 }
	  	trade = { level = 0 value = 20 }
        land = { level = 0 value = 0 } 
        naval = { level = 0 value = 0 } 
    } 
} 

