#powhatan

country = { 
    tag = POW 
    colonialattempts = 0 
    colonialnation = no 
    major = no 
    colonists = 0 
    cancelledloans = 0 
    extendedloans = 0 
    treasury = 99 
    inflation = 0 
    merchants = 0.083333 
    religion = { type = thunderbird }
    culture = { type = iroquis }
    diplomacy = {
     }
    knownprovinces = { 
	52 53 54 55 56 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 83 84 85 86 87 88 89 90 91 100 101 102 103 104 }
    ownedprovinces = { 
        69 } 
    controlledprovinces = { 
        69 } 
    nationalprovinces = { 
        69 } 
    city = {         fortress = { level = 1 }  
        population = 1000
        location = 69 
        capital = yes 
        } 
    technology = {
		stability = { level = 2 value = 42 }
        infra = { level = 0 value = 20 }
	  	trade = { level = 0 value = 20 }
        land = { level = 0 value = 0 } 
        naval = { level = 0 value = 0 } 
    } 
} 