# Socotra #

country = { 
	tag = SOC 
	ai = "SmallTrade1_ai.txt"
	colonialattempts = 0 
	colonialnation = no 
	major = no 
	colonists = 0 
	cancelledloans = 0 
	extendedloans = 0 
	treasury = 50
	inflation = 0 
	diplomats = 0
	merchants = 0
    religion = { type = miaphysite }
	culture = { type = somali type = arabic type = ethiopian }
	diplomacy = {
		relation = { tag = OMA value = 100 }
		relation = { tag = ADE value = -100 }
	} 

	knownprovinces = { 
		488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503 504 505 506 507 508
		532 533 534 535 536 537 538 539 540 541 741 742 743 744 745 746 747 748 749 750 751
		752 753 754 755 756 757 759 760
		1003 1004 1005 1059 1060 1061 1062 1063 1064 1065 1066 1067 1068 1069
		1134 1135 1136 1359 1363 1411 1437 1453 1454
	}

	ownedprovinces = { 
		756 } 
	controlledprovinces = { 
		756 } 
	nationalprovinces = { 
		756 } 

	city = {
		name = "Suq"
		fortress = { level = 1 }   
		population = 1100
		location = 756 
		capital = yes 
		} 

	technology = {
		stability = { level = 1 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 1 value = 0 }
		land = { level = 0 value = 0 } 
		naval = { level = 0 value = 0 } 
	}
}
