# Permia #

country = { 
    tag = PRM
    ai = "MOS_1419_Standard.txt"
    colonialattempts = 0 
    colonialnation = no
    major = no 
    colonists = 0
    cancelledloans = 0 
    extendedloans = 0 
    treasury = 100 
    inflation = 0 
    merchants = 0 
    religion = { type = e_pagan } 
    culture = { type = ugric } 
    diplomacy = { 
    	relation = { tag = MOS value = 100 }
    	relation = { tag = NVG value = 100 }
    	relation = { tag = WHR value = -100 }
    	relation = { tag = PSK value = -50 }
    	relation = { tag = RYA value = -50 }
    	relation = { tag = TVE value = -50 }
    	relation = { tag = YRL value = -50 }
    	relation = { tag = POL value = -50 }
    	relation = { tag = LIT value = -50 }
    }
	knownprovinces = { # European minor - Permia
		Russia Steppe Ob Sibir Ukraine Caucasus "Russian North" Kazakhstan
	} 
    ownedprovinces = { 1575 1580 1581 } 
    controlledprovinces = { 1575 1580 1581 } 
    nationalprovinces = { 1575 1580 1581 } 

    city = {         
    	fortress = { level = 1 }   
        population = 4500
        location = 1580
        capital = yes 
    } 
    city = {         
        population = 1200
        location = 1581
    } 
    city = {         
        population = 1000
        location = 1575
    } 

	technology = {
		stability = { level = 0 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 0 value = 0 } 
		naval = { level = 0 value = 0 } 
	}
}
