# Oyo #

country = {
	tag = OYO
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 150
	inflation = 0
	merchants = 0
	religion = { type = pagan }
	culture = { type = yorumba }
	diplomacy = {
		relation = { tag = SON value = 25 }
		relation = { tag = BEN value = 75 }
		relation = { tag = HAS value = 75 }
	}
	knownprovinces = {
		744 791 792 793 794 1487 1488 1489 1490 1491 1492 1493 1494 1495 1496 1497 1498 1499 1500 1501 1502 1595
	}
	ownedprovinces = {
		1500
	}
	controlledprovinces = {
		1500
	}
	nationalprovinces = {
		1500 1501 1502
	}

	city = {
		fortress = { level = 1 }
		population = 18000
		location = 1500
		capital = yes
	}

	technology = {
		stability = { level = 0 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 0 value = 0 }
		land = { level = 0 value = 0 } 
		naval = { level = 0 value = 0 } 
	}
}
