#Northern Yuan

#-----------------------------------------------------------------------------------------------

country = {
	tag = NYN
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 100
	inflation = 0
	merchants = 0.083333
	religion = { type = pagan }
	culture = {
		type = mongol
	}
	diplomacy = {
		relation = { tag = CHI value = 150 }
		relation = { tag = KOR value = -25 }
		relation = { tag = CHG value = -25 }
	}
	knownprovinces = {
		Amur Baikal Jenisej Korea Lena Manchuria Peking
		654 844 845 883 886 940 942 943 947 1603
	}
	ownedprovinces = {
		595 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611
	}
	controlledprovinces = {
		595 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611
	}
	nationalprovinces = {
		595 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611
	}

	city = {
		population = 1200
		location = 595
	}
	city = {
		population = 1200
		location = 597
	}
	city = {
		population = 1200
		location = 598
	}
	city = {
		population = 1200
		location = 599
	}
	city = {
		population = 1200
		location = 600
	}
	city = {
		population = 1200
		location = 601
	}
	city = {
		population = 1200
		location = 602
	}
	city = {
		fortress = { level = 1 }
		population = 2500
		location = 603
		capital = yes
	}
	city = {
		population = 1200
		location = 604
	}
	city = {
		population = 1200
		location = 605
	}
	city = {
		population = 1200
		location = 606
	}
	city = {
		population = 1200
		location = 607
	}
	city = {
		population = 1200
		location = 608
	}
	city = {
		population = 1200
		location = 609
	}
	city = {
		population = 1200
		location = 610
	}
	city = {
		population = 1200
		location = 611
	}

	landunit = {
		id = { type = 9423 id = 859 }
		name = "Yuan Army"
		location = 603
		infantry = 3000
		cavalry = 12000
		artillery = 0
	}
	technology = {
		stability = { level = 0 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 1 value = 0 }
		land = { level = 0 value = 0 } 
		naval = { level = 0 value = 0 } 
	}
}

#-----------------------------------------------------------------------------------------------
