#sahnish/arikara

country = { 
    tag = SAH 
    colonialattempts = 0 
    colonialnation = no 
    major = no 
    colonists = 0 
    cancelledloans = 0 
    extendedloans = 0 
    treasury = 99 
    inflation = 0 
    merchants = 0.083333 
    religion = { type = medicinewheel }
    culture = { type = dakota }
    diplomacy = {
        } 
    knownprovinces = { 
      	46 48 49 50 52 53 54 55 56 57 58 59 60 61 62 63 64 67 68 72 73 74 75 76 77 78 79 86 87 }
    ownedprovinces = { 
        58 } 
    controlledprovinces = { 
        58 } 
    nationalprovinces = { 
        57 58 } 
    city = {         fortress = { level = 1 }  
        population = 2000
        location = 58 
        capital = yes 
        } 
    technology = {
		stability = { level = 2 value = 42 }
        infra = { level = 0 value = 20 }
	  	trade = { level = 0 value = 20 }
        land = { level = 0 value = 0 } 
        naval = { level = 0 value = 0 } 
    } 
} 

