# Navajo/Apache/Ute #

country = { 
    tag = APA 
    colonialattempts = 0 
    colonialnation = no 
    major = no 
    colonists = 0 
    cancelledloans = 0 
    extendedloans = 0 
    treasury = 100
    inflation = 0 
    merchants = 0.083333 
    religion = { type = peyote }
    culture = { type = navajo }
    diplomacy = { 
    } 
    knownprovinces = { 
      	14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 822 1477 1478 1479 1480 1481
    }
    ownedprovinces = { 
        19 1477 1478 1479 } 
    controlledprovinces = { 
        19 1477 1478 1479 } 
    nationalprovinces = { 
        19 1477 1478 1479 } 
    city = {         fortress = { level = 1 }  
        population = 2000
        location = 1477 
        capital = yes 
        } 
    city = {
        population = 1000
        location = 1478 
        } 
    city = {
        population = 1000
        location = 1479 
        } 
    city = {
        population = 1000
        location = 19 
        } 
    technology = {
		stability = { level = 2 value = 42 }
        infra = { level = 0 value = 20 }
	  	trade = { level = 0 value = 20 }
        land = { level = 0 value = 0 } 
        naval = { level = 0 value = 0 } 
    } 
} 

