#choctaw

country = { 
    tag = CHO 
    colonialattempts = 0 
    colonialnation = no 
    major = no 
    colonists = 0 
    cancelledloans = 0 
    extendedloans = 0 
    treasury = 99 
    inflation = 0 
    merchants = 0.083333 
    religion = { type = gorgetism }
    culture = { type = creek }
    diplomacy = {
        } 
    knownprovinces = { 
      	44 45 46 47 48 49 50 51 52 53 54 55 56 57 59 60 61 62 63 64 67 68 72 86 87 1481 }
    ownedprovinces = { 
        51 52 53 } 
    controlledprovinces = { 
        51 52 53 } 
    nationalprovinces = { 
        51 52 53 } 
    city = {         fortress = { level = 1 }  
        population = 2000
        location = 53 
        capital = yes 
        }
    city = {
        population = 1000
        location = 51 
        } 
    city = {
        population = 1000
        location = 52 
        }  
    technology = {
		stability = { level = 2 value = 42 }
        infra = { level = 0 value = 20 }
	  	trade = { level = 0 value = 20 }
        land = { level = 0 value = 0 } 
        naval = { level = 0 value = 0 } 
    } 
} 

