# China (Chung Kuo) #

country = { 
    tag = CHI
    ai = "CHI_1419_ZengHe.txt"
    colonialattempts = 0 
    colonialnation = no 
    major = no 
    colonists = 0 
    cancelledloans = 0 
    extendedloans = 0 
    treasury = 500
    inflation = 0 
    merchants = 0.083333 
    religion = { type = confucianism }
    culture = {  
	type = mongolc
	type = han 
    }   
    diplomacy = { 
   	relation = { tag = NYN value = 150 }
    } 
    knownprovinces = { 
         595 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611 625 626 628 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647 648 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665 666 677 683 684 685 686 687 688 689 705 940 941 942 943 944 1018 1019 1020 1021 1081 1082 1083 1084 1085 1086 1087 1088 1145 1146 1147 1149 1150 1151 1152 1205 1207 1208 1347 1349 1350 1351 1352 1353 1356 1544 1545 1546 1553 1554 1555 1556 1557 1558 1559 1560 1561 1562 1563 1564 1565 1566 1567
# Tibet
		1539 1540 1541 1542 1543
# Bit of Burma
		1547 1548 1549 1550 
# Laos
		669 1551 1552
# Ayutthaya
		670 674 675
# Cambodia
		667 668
# The Silk Road
		1592 1598 1599 1600 1601 1602 1603 1604 1605 1606 1607 1608
    }
    ownedprovinces = { 
        635 636 637 638 639 640 643 644 645 646 647 648 649 650 651 652 653 654 655 656 657 658 659 660 661 1544 1545 1553 1555 1556 1557 1558 1559 1560 1561 1562 1563 1564 1565 1566 1567 } 
    controlledprovinces = { 
        635 636 637 638 639 640 643 644 645 646 647 648 649 650 651 652 653 654 655 656 657 658 659 660 661 1544 1545 1553 1555 1556 1557 1558 1559 1560 1561 1562 1563 1564 1565 1566 1567 } 
    nationalprovinces = { 
        635 643 644 645 646 647 648 649 650 651 652 653 654 655 656 657 658 659 660 661 1544 1553 1555 1556 1557 1558 1559 1560 1561 1562 1563 1564 1565 1566 1567  } 
    city = {         fortress = { level = 1 }  
        population = 50000
        location = 650 
        } 
    city = {         fortress = { level = 1 }  
        population = 25000
        location = 660 
        } 
    city = {         fortress = { level = 1 }  
        population = 24000
        location = 661 
        } 
    city = {         fortress = { level = 1 }  
        population = 25000
        location = 659 
        } 
    city = {         fortress = { level = 1 }  
        population = 25000
        location = 658 
        } 
    city = {         fortress = { level = 1 }  
        population = 50000
        location = 657 
        } 
    city = {         fortress = { level = 1 }  
        population = 25000
        location = 656 
        } 
    city = {         fortress = { level = 1 }  
        population = 26000
        location = 655 
        } 
    city = {
        population = 50000
        location = 654
    } 
    city = {         fortress = { level = 1 }  
        population = 50000
        location = 653 
    } 
    city = {         fortress = { level = 1 }  
        population = 25000
        location = 652 
        } 
    city = {
        population = 25000
        location = 651 
        } 
    city = {         fortress = { level = 1 }  
        population = 80000
        location = 649
        capital = yes 
    } 
    city = {         fortress = { level = 1 }  
        population = 40000
        location = 647 
        } 
    city = {         fortress = { level = 1 }  
        population = 13000
        location = 648 
        } 
    city = {
        population = 3000
        location = 1544 
        } 
    city = {
    	fortress = { level = 1 }
        population = 7000
        location = 1545 
    } 
   city = {
        population = 6000
        location = 1559 
        } 
    city = {
        population = 6000
        location = 1560 
        } 
    city = {
        population = 6000
        location = 1561 
        } 
    city = {
        population = 10000
        location = 1553 
        } 
    city = {
        population = 8000
        location = 1557 
        } 
    city = {
        population = 8000
        location = 1558 
        } 
    city = {
        population = 10000
        location = 1556 
        } 
    city = {
        population = 25000
        location = 1563 
        } 
    city = {
        population = 25000
        location = 1562 
        } 
    city = {
        population = 25000
        location = 1566 
        } 
    city = {
        population = 25000
        location = 1564 
        } 
    city = {
        population = 25000
        location = 1565 
        } 
    city = {
        population = 25000
        location = 1567 
        } 
    city = {
        population = 25000
        location = 1555 
        } 
city = {         fortress = { level = 1 }  
        population = 30000
        location = 643 
        } 
    city = {         fortress = { level = 1 }  
        population = 30000
        location = 635 
        } 
    city = {         fortress = { level = 1 }  
        population = 12600
        location = 644 
        } 
    city = {         fortress = { level = 1 }  
        population = 30000
        location = 645 
        } 
    city = {         fortress = { level = 1 }  
        population = 20000
        location = 646 
        } 
    city = {         fortress = { level = 1 }  
        population = 18300
        location = 640 
        } 
    city = {         fortress = { level = 1 }  
        population = 15700
        location = 639 
        } 
    city = {         fortress = { level = 1 }  
        population = 11500
        location = 636 
        } 
    city = {         fortress = { level = 1 }  
        population = 10400
        location = 638 
        } 
    city = {         fortress = { level = 1 }  
        population = 10600
        location = 637 
        } 
    landunit = { 
        id = { type = 9423 id = 846 } 
        name = "Manchurian Army" 
        location = 643
        infantry = 40000 
        cavalry = 30000 
        artillery = 0 
        } 
    landunit = { 
        id = { type = 9423 id = 995 } 
        name = "Imperial Army" 
        location = 649 
        infantry = 50000 
        cavalry = 20000 
        artillery = 0 
    }
    technology = {
		stability = { level = -2 value = 0 }
        infra = { level = 0 value = 0 }
	  	trade = { level = 1 value = 0 }
        land = { level = 0 value = 0 } 
        naval = { level = 0 value = 0 } 
    } 
} 

