# Chumash #

country = { 
    tag = CHU 
    colonialattempts = 0 
    colonialnation = no 
    major = no 
    colonists = 0 
    cancelledloans = 0 
    extendedloans = 0 
    treasury = 100
    inflation = 0 
    merchants = 0.083333 
    religion = { type = medicinewheel }
    culture = { type = penutian }
    diplomacy = { 
    } 
    knownprovinces = { 
      	9 10 11 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 822 1474 1475 1476 1477 1478 1479 1480 1481
    }
    ownedprovinces = { 
        11 1476 1475 } 
    controlledprovinces = { 
        11 1476 1475 } 
    nationalprovinces = { 
        14 11 1476 1475 } 
    city = {         fortress = { level = 1 }  
        population = 2000
        location = 11 
        capital = yes 
        } 
    city = {
        population = 1000
        location = 1475 
        } 
    city = {
        population = 1000
        location = 1476 
        } 
    technology = {
		stability = { level = 2 value = 42 }
        infra = { level = 0 value = 20 }
	  	trade = { level = 0 value = 20 }
        land = { level = 0 value = 0 } 
        naval = { level = 0 value = 0 } 
    } 
} 

