# The Mameluks #

country = { 
    tag = MAM
    colonialattempts = 0 
    colonialnation = no 
    major = no 
    colonists = 0 
    cancelledloans = 0 
    extendedloans = 0 
    treasury = 200 
    inflation = 0 
    merchants = 0 
    religion = { type = sunni }
    culture = { type = arabic }
    diplomacy = { 
    	relation = { tag = KNI value = 50 }
    	relation = { tag = TUR value = -100 }
   	relation = { tag = ARA value = 100 }
    } 
    knownprovinces = {  
                      296 318 319 320 321 322 355 356 357 358 359 360 361 
                      362 363 364 365 366 367 368 370 389 390 391 392 393 
                      394 395 396 397 398 399 400 401 402 403 404 405 406 
                      407 426 427 429 430 435 436 437 438 439 440 441 443 
                      444 445 455 456 457 458 462 463 464 465 466 467 468 
                      469 470 471 472 473 474 475 476 477 478 479 480 481 
                      482 483 484 485 486 487 488 489 490 491 492 493 494 
                      495 496 497 498 499 500 501 502 503 504 505 506 507 
                      508 509 529 530 531 532 533 534 535 732 733 734 735 
                      736 737 738 739 740 741 742 743 744 745 746 747 748 
                      749 750 751 752 753 754 755 757 819 820 821 982 983 
                      984 985 986 987 988 989 990 991 992 993 994 995 996 
                      997 998 999 1000 1001 1002 1003 1004 1005 1006 1007 
                      1008 1009 1010 1011 1012 1013 1014 1015 1016 1017 
                      1059 1060 1061 1062 1063 1064 1065 1363 1609 
                      1610 1611 1613 
    } 
    ownedprovinces = { 
            490 741 742 743 744 745 746 494 493 492 491 495 }
    controlledprovinces = { 
            490 741 742 743 744 745 746 494 493 492 491 495 }
    nationalprovinces = { 
            744 745 746 }
    casusbelliprovinces = {
            747 743 494 493 492 491 490 495
    }
    city = {
    	fortress = { level = 1 }  
        population = 30000
        location = 490 
    }
    city = {         fortress = { level = 1 } 
        population = 10000
        location = 491 
    } 
    city = {         fortress = { level = 1 }  
        population = 10000
        location = 492 
    } 
    city = {         fortress = { level = 1 }  
        population = 6000
        location = 493 
    } 
    city = {   fortress = { level = 1 } 
        population = 1000
        location = 494 
        } 
    city = {         fortress = { level = 1 }  
        population = 50000
        location = 746 
        capital = yes
        } 
    city = {         fortress = { level = 1 }  
        population = 15000
        location = 745 
        } 
    city = {         fortress = { level = 1 }  
        population = 25000
        location = 744 
        } 
    city = {         fortress = { level = 1 }
        population = 1000
        location = 743 
        } 
    city = {         fortress = { level = 1 }
        population = 1000
        location = 742 
        } 
    city = {         fortress = { level = 1 }  
        population = 7000
        location = 741 
    } 
    city = {         fortress = { level = 1 }  
        population = 2100
        location = 495 
        } 
    landunit = { 
        id = { type = 9423 id = 626 } 
        name = "Egyptian Army" 
        location = 744 
        infantry = 10000 
        cavalry = 10000 
        artillery = 0 
        } 

    landunit = { 
        id = { type = 9666 id = 1 } 
        name = "Syrian Army" 
        location = 492 
        infantry = 10000 
        cavalry = 12000 
        artillery = 0
        } 
    technology = {
		stability = { level = -2 value = 42 }
      	infra = { level = 0 value = 10 }
		trade = { level = 0 value = 70 }
      	land = { level = 0 value = 50 } 
      	naval = { level = 0 value = 0 } 
    } 
} 