# Sultanate of Delhi #

country = { 
    tag = DLH
    colonialattempts = 0 
    colonialnation = no 
    major = no 
    badboy = 15
    colonists = 0 
    cancelledloans = 0 
    extendedloans = 0 
    treasury = 100 
    inflation = 0 
    merchants = 0.083333 
    religion = { type = sunni }
    culture = { type = turkish }
    revoltrisk = { date = { day = 0 month = january year = 1347 } value = 15 }
    diplomacy = { 
    	relation = { tag = MLW value = -100 }
    	relation = { tag = GUJ value = -100 }
    	relation = { tag = RAJ value = -100 }
    	relation = { tag = TIM value = -100 }
    	relation = { tag = VIJ value = -100 }
    } 
    knownprovinces = { 
# Indian Mainland    
        539 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575 576 671 672 1520 1521 1522 1523 1545 1546
# Afghanistan
		1524 1525 1526 1527 1528 1531 1591 1592
# Tibet
		1539 1540 1541 1542 1543
# Indian Sea Zones
		1138 1140 1066 1069 1070 1071 1072 1073 1074 1078
# Persian Gulf
		504 533 534 535 536 537 538 1063 1065 1363
    }
    ownedprovinces = { 
        547 554 555 557 558 559 560 561 564 565 539 540 546 552 553 562 543 544 545 1520 1521 1523 550 551 563 566 548 549 571 572 575 568 } 
    controlledprovinces = { 
        547 554 555 557 558 559 560 561 564 565 539 540 546 552 553 562 543 544 545 1520 1521 1523 550 551 563 566 548 549 571 572 575 568 } 
    nationalprovinces = { 
        539 540 541 543 544 545 546 547 1520 1521 1523 } 
    city = {         fortress = { level = 1 }  
        population = 60000
        location = 543 
        capital = yes 
    } 
    city = {         fortress = { level = 1 }  
        population = 29000
        location = 545 
        } 
    city = {         fortress = { level = 1 }  
        population = 50000
        location = 544 
        } 
    city = {
        population = 20000
        location = 1520 
        } 
    city = {
        population = 16000
        location = 1521 
        } 
    city = {         fortress = { level = 1 }  
        population = 15000
        location = 1523 
        } 
    city = {         fortress = { level = 1 }  
        population = 15000
        location = 553 
        } 
    city = {         fortress = { level = 1 }  
        population = 15000
        location = 552 
        } 
    city = {         fortress = { level = 1 }  
        population = 19000
        location = 562 
    } 
    city = {         fortress = { level = 1 }  
        population = 20000
        location = 546 
    } 
	city = {
		fortress = { level = 1 }
		population = 7000
		location = 548
	}
	city = {
		fortress = { level = 1 }
		population = 25000
		location = 549
	}
	city = {
		fortress = { level = 1 }
		population = 19000
		location = 550
	}
	city = {
		fortress = { level = 1 }
		population = 20000
		location = 551
	}
	city = {
		population = 22000
		location = 563
	}
	city = {
		fortress = { level = 1 }
		population = 30000
		location = 566
	}
	city = {
		population = 18000
		location = 568
	}
	city = {
		fortress = { level = 1 }
		population = 20000
		location = 571
	}
	city = {
		fortress = { level = 1 }
		population = 10000
		location = 572
	}
	city = {
		fortress = { level = 1 }
		population = 10000
		location = 575
	}
    city = {         fortress = { level = 1 }  
        population = 20000
        location = 539 
    } 
    city = {         fortress = { level = 1 }  
        population = 20000
        location = 540 
    } 
	city = {
		fortress = { level = 1 }
		population = 22000
		location = 560
	}
	city = {
		fortress = { level = 1 }
		population = 22000
		location = 561
	}
	city = {
		fortress = { level = 1 }
		population = 8000
		location = 564
	}
	city = {
		population = 20000
		location = 565
	}
    city = {         fortress = { level = 1 }  
        population = 20000
        location = 547 
    } 
city = {         fortress = { level = 1 }  
        population = 50000
        location = 559 
    } 
	city = {         fortress = { level = 1 }  
        population = 23000
        location = 555 
    } 
    city = {         fortress = { level = 1 }  
        population = 19000
        location = 557 
    } 
    city = {         fortress = { level = 1 }  
        population = 22000
        location = 558 
    } 
    city = {         fortress = { level = 1 }  
        population = 18000
        location = 554 
    } 
    landunit = { 
        id = { type = 9423 id = 1005 } 
        name = "Delhi Army" 
        location = 543 
        infantry = 5000 
        cavalry = 5000
        artillery = 0 
    } 
    technology = {
		stability = { level = -3 value = 42 }
        infra = { level = 1 value = 0 }
	  	trade = { level = 1 value = 0 }
        land = { level = 0 value = 0 } 
        naval = { level = 0 value = 0 } 
    } 
}