#neutrals (attiwandaronk)

country = { 
    tag = NEU 
    colonialattempts = 0 
    colonialnation = no 
    major = no 
    colonists = 0 
    cancelledloans = 0 
    extendedloans = 0 
    treasury = 99 
    inflation = 0 
    merchants = 0.083333 
    religion = { type = thunderbird }
    culture = { type = iroquis }
    diplomacy = {
     }
    knownprovinces = { 
	60 65 66 67 68 69 70 71 72 81 82 83 84 85 87 87 88 89 90 91 92 97 98 100 106 107 1369 1370 1371 1372 }
    ownedprovinces = { 
        92 } 
    controlledprovinces = { 
        92 } 
    nationalprovinces = { 
        92 } 
    city = {         fortress = { level = 1 }  
        population = 1000
        location = 92 
        capital = yes 
        } 
    technology = {
		stability = { level = 2 value = 42 }
        infra = { level = 0 value = 20 }
	  	trade = { level = 0 value = 20 }
        land = { level = 0 value = 0 } 
        naval = { level = 0 value = 0 } 
    } 
} 