
#Benin#

country = { 
    tag = BEN 
    colonialattempts = 0 
    colonialnation = no 
    major = no 
    colonists = 0 
    cancelledloans = 0 
    extendedloans = 0 
    treasury = 200 
    inflation = 0 
    merchants = 0 
    religion = { type = pagan }
    culture = { type = yorumba }
    diplomacy = { 
		relation = { tag = HAS value = 75 }
		relation = { tag = OYO value = 75 }
        } 
    knownprovinces = { 
		791 792 793 794 795 1487 1488 1489 1490 1491 1492 1493 1494 1495 1496 1497 1498 1499 1500 1501 1502 } 
    ownedprovinces = { 
        791 792 793 } 
    controlledprovinces = { 
        791 792 793 } 
    nationalprovinces = { 
        791 792 793 1500 1501 1502 } 
    city = {
    	fortress = { level = 1 }  
        population = 15000
        location = 791
	capital = yes
    } 
    city = {
    	fortress = { level = 1 }  
        population = 15000
        location = 792
    } 
    city = {
    	fortress = { level = 1 }  
        population = 15000
        location = 793
    } 
    technology = {
    	stability = { level = 2 value = 42 }
      	infra = { level = 0 value = 10 }
      	trade = { level = 0 value = 70 }
      	land = { level = 0 value = 50 } 
      	naval = { level = 0 value = 0 } 
    } 
} 


