#saux-fox

country = { 
    tag = SXF 
    colonialattempts = 0 
    colonialnation = no 
    major = no 
    colonists = 0 
    cancelledloans = 0 
    extendedloans = 0 
    treasury = 99 
    inflation = 0 
    merchants = 0.083333 
    religion = { type = thunderbird }
    culture = { type = shawnee }
    diplomacy = {
        } 
    knownprovinces = { 
      	46 48 49 50 52 53 54 55 56 57 58 59 60 61 62 63 64 67 68 71 72 73 74 75 76 77 78 79 80 81 82 86 87 1369 1370 1371 1372 }
    ownedprovinces = { 
        73 } 
    controlledprovinces = { 
        73 } 
    nationalprovinces = { 
        73 80 } 
    city = {         fortress = { level = 1 }  
        population = 2000
        location = 73 
        capital = yes 
        }  
    technology = {
		stability = { level = 2 value = 42 }
        infra = { level = 0 value = 20 }
	  	trade = { level = 0 value = 20 }
        land = { level = 0 value = 0 } 
        naval = { level = 0 value = 0 } 
    } 
} 

