#menominee (kiash machatiwuk)

country = { 
    tag = KMK 
    colonialattempts = 0 
    colonialnation = no 
    major = no 
    colonists = 0 
    cancelledloans = 0 
    extendedloans = 0 
    treasury = 99 
    inflation = 0 
    merchants = 0.083333 
    religion = { type = thunderbird }
    culture = { type = huron }
    diplomacy = {
     }
    knownprovinces = { 
	93 79 80 74 75 76 77 78 94 95 96 97 98 92 81 82 133 107 106 58 59 60 57 72 71 83 90 91 89 100 99 1369 1370 1371 1372 }
    ownedprovinces = { 
        79 80 74 } 
    controlledprovinces = { 
        79 80 74 } 
    nationalprovinces = { 
        93 79 80 74 } 
    city = {         fortress = { level = 1 }  
        population = 1000
        location = 79 
        capital = yes 
        } 
    city = {
        population = 1000
        location = 80 
        }
    city = {
        population = 1000
        location = 74 
        } 
    technology = {
		stability = { level = 2 value = 42 }
        infra = { level = 0 value = 20 }
	  	trade = { level = 0 value = 20 }
        land = { level = 0 value = 0 } 
        naval = { level = 0 value = 0 } 
    } 
} 