#Blue Horde#

country = { 
    tag = BHR 
    colonialattempts = 0 
    colonialnation = no 
    major = no 
    colonists = 0 
    cancelledloans = 0 
    extendedloans = 0 
    treasury = 100 
    inflation = 0 
    merchants = 0.083333 
    religion = { type = sunni }
    culture = { 
		type = altai
		type = mongol
		 }
    diplomacy = { 
    	relation = { tag = MOS value = 100 refusetrade = no }  
    	relation = { tag = RYA value = 100 refusetrade = no } 
    	relation = { tag = TVE value = 100 refusetrade = no } 
    	relation = { tag = TIM value = -200 refusetrade = no } 
    }
    knownprovinces = { 471
                      478 479 480 481 482 483 484 485 486 487 488 489 490 
                      491 492 493 494 495 496 497 498 510 511 512 513 514 
                      515 516 517 518 519 520 521 522 523 524 525 526 527 
                      528 529 530 531 532 533 534 535 578 579 742 744 745 
                      746 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 
			464 1013 1014 1015 1016 1017 1326 1327 1529 1530 1531 
			465 1532 1533 1534 1535 1536 1570 1571 1573 1592 1594 
			    1609 1610 1611 1613 448 272 271 270 279 461 462 295 450
			451 296 294 293 298 297 299 292 300 291 288 284 287 285 286 280 281 278 274 277
			316 325 317 324 477 476 475 474 473 472 470 469 318 319
    }
    ownedprovinces = { 
        296 461 462 446 447 451 452 453 454 455 456 457 458 459 460 463 466 467 468 } 
    controlledprovinces = { 
        296 461 462 446 447 451 452 453 454 455 456 457 458 459 460 463 466 467 468 } 
    nationalprovinces = { 
        446 447 449 451 452 453 454 455 456 457 458 459 460 463 464 465 466 467 468 } 
    city = {         fortress = { level = 1 }  
        population = 9000
        location = 461 
        } 
    city = {         fortress = { level = 1 }  
        population = 12000
        location = 296 
        }   
    city = {         fortress = { level = 1 }  
        population = 6000
        location = 462 
        } 
    city = {         fortress = { level = 1 }  
        population = 10500
        location = 454 
        } 
    city = {         fortress = { level = 1 }  
        population = 10100
        location = 446 
        } 
    city = {         fortress = { level = 1 }  
        population = 10100
        location = 447 
        } 
    city = {         fortress = { level = 1 }  
        population = 8000
        location = 452 
        } 
    city = {         fortress = { level = 1 }  
        population = 7500
        location = 451 
        } 
    city = {         fortress = { level = 1 }  
        population = 4500
        location = 453 
        } 
    city = {         fortress = { level = 1 }   
        population = 10000
        location = 457 
        } 
    city = {         fortress = { level = 1 }  
        population = 3000
        location = 456 
        } 
    city = {         fortress = { level = 1 }  
        population = 3000
        location = 455 
        } 
    city = {         fortress = { level = 1 }  
        population = 5000
        location = 458 
        capital = yes 
        } 
    city = {         fortress = { level = 1 }  
        population = 6000
        location = 459 
        } 
    city = {         fortress = { level = 1 }  
        population = 8000
        location = 460 
        } 
    city = {         fortress = { level = 1 }  
        population = 17500
        location = 463 
        } 
    city = {         fortress = { level = 1 }   
        population = 5500
        location = 466 
        } 
    city = {         fortress = { level = 1 }  
        population = 5500
        location = 467 
        } 
    city = {         fortress = { level = 1 }  
        population = 5500
        location = 468 
    }  
    landunit = { 
        id = { type = 9423 id = 959 } 
        name = "Golden Horde" 
        location = 454 
        infantry = 2000
        cavalry = 20000
        artillery = 0 
        } 
    technology = {
		stability = { level = -3 value = 42 }
        infra = { level = 0 value = 20 }
	  	trade = { level = 0 value = 20 }
        land = { level = 0 value = 50 } 
        naval = { level = 0 value = 0 } 
    } 
} 

