# Creek #

country = { 
    tag = CRE 
    colonialattempts = 0 
    colonialnation = no 
    major = no 
    colonists = 0 
    cancelledloans = 0 
    extendedloans = 0 
    treasury = 99 
    inflation = 0 
    merchants = 0.083333 
    religion = { type = gorgetism }
    culture = { type = creek }
    diplomacy = { 
        } 
    knownprovinces = { 
      	46 47 48 49 50 52 53 54 55 56 60 61 62 63 64 67 68 72 86 87 } 
    ownedprovinces = { 
        48 54 } 
    controlledprovinces = { 
        48 54 } 
    nationalprovinces = { 
        48 54 } 
    city = {         fortress = { level = 1 }  
        population = 1000
        location = 48 
        capital = yes 
        } 
    city = {
        population = 1000
        location = 54 
        } 
    technology = {
		stability = { level = 2 value = 42 }
        infra = { level = 0 value = 20 }
	  	trade = { level = 0 value = 20 }
        land = { level = 0 value = 0 } 
        naval = { level = 0 value = 0 } 
    } 
} 

