#Nubia#

country = { 
    tag = NUB 
    colonialattempts = 0 
    colonialnation = no 
    major = no 
    colonists = 0 
    cancelledloans = 0 
    extendedloans = 0 
    treasury = 100
    inflation = 0 
    merchants = 0.083333 
    religion = { type = miaphysite }
    culture = { type = nubian }
    diplomacy = { 
    } 
    knownprovinces = { 
 	488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503 504 505 506 507 508
	532 533 534 535 536 537 538 539 540 541 741 742 743 744 745 746 747 748 749 750 751
	752 753 754 755 756 757 759 760
	1003 1004 1005 1059 1060 1061 1062 1063 1064 1065 1066 1067 1068 1069
	1134 1135 1136 1359 1363 1411 1437 1453 1454 } 
    ownedprovinces = { 
        747 748 749 750 751 } 
    controlledprovinces = { 
        747 748 749 750 751 } 
    nationalprovinces = { 
        748 749 750 751 } 
    city = {
    	fortress = { level = 1 }  
        population = 3500
        location = 750 
        capital = yes 
    } 
    city = {
    	fortress = { level = 1 }  
        population = 3000
        location = 751
    } 
    city = {          fortress = { level = 1 }
        population = 4500
        location = 747 
        } 
    city = {
    	fortress = { level = 1 }  
        population = 1500
        location = 748 
    } 
    city = {
    	fortress = { level = 1 }  
        population = 2000
        location = 749 
    } 
    landunit = { 
        id = { type = 9423 id = 964 } 
        name = "Nubian Army" 
        location = 750 
        infantry = 5000
        cavalry = 5000 
        artillery = 0 
    } 
    technology = {
		stability = { level = -2 value = 42 }
        infra = { level = 1 value = 20 }
	  	trade = { level = 1 value = 20 }
        land = { level = 1 value = 50 } 
        naval = { level = 0 value = 0 } 
    } 
} 

