# Kongo #

country = { 
    tag = KON 
    colonialattempts = 0 
    colonialnation = no 
    major = no 
    colonists = 0 
    cancelledloans = 0 
    extendedloans = 0 
    treasury = 200 
    inflation = 0 
    merchants = 0 
    religion = { type = pagan }
    culture = { type = kongolese }
    diplomacy = { 
        } 
    knownprovinces = { 
		787 788 789 793 1503 1504 1505 1506 } 
    ownedprovinces = { 
        1503 1504 1505 1506 } 
    controlledprovinces = { 
        1503 1504 1505 1506 } 
    nationalprovinces = { 
        787 788 789 1503 1504 1505 1506 } 
    city = {         fortress = { level = 1 }  
        population = 18000
        location = 1506 
        capital = yes
        } 
    city = {         fortress = { level = 1 }  
        population = 8000
        location = 1503
        } 
    city = {         fortress = { level = 1 }  
        population = 10000
        location = 1504
        } 
    city = {         fortress = { level = 1 }  
        population = 10000
        location = 1505
        } 
    technology = {
		stability = { level = 3 value = 42 }
      	infra = { level = 0 value = 10 }
		trade = { level = 0 value = 70 }
      	land = { level = 0 value = 50 } 
      	naval = { level = 0 value = 0 } 
    } 
} 


