# Dakota #

country = { 
    tag = DAK 
    colonialattempts = 0 
    colonialnation = no 
    major = no 
    colonists = 0 
    cancelledloans = 0 
    extendedloans = 0 
    treasury = 99 
    inflation = 0 
    merchants = 0.083333 
    religion = { type = thunderbird }
    culture = { type = dakota }
    diplomacy = { 
    }
    knownprovinces = { 
	56 58 60 71 72 73 74 75 76 77 78 79 80 81 82 83 90 91 93 94 95 96 98 }
    ownedprovinces = { 
        75 76 77 78 } 
    controlledprovinces = { 
        75 76 77 78 } 
    nationalprovinces = { 
        75 76 77 78 79 } 
    city = {         fortress = { level = 1 }  
        population = 1000
        location = 76 
        capital = yes 
        } 
    city = {
        population = 1000
        location = 75 
        } 
    city = {
        population = 1000
        location = 77 
        } 
    city = {
        population = 1000
        location = 78
        } 
    technology = {
		stability = { level = 2 value = 42 }
        infra = { level = 0 value = 20 }
	  	trade = { level = 0 value = 20 }
        land = { level = 0 value = 0 } 
        naval = { level = 0 value = 0 } 
    } 
} 

