# Sus #

country = {
	tag = SUS
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 150
	inflation = 0
	merchants = 0
	religion = { type = sunni }
	culture = { type = berber }
	diplomacy = {
		relation = { tag = SON value = 100 }
		relation = { tag = TLE value = 100 }
		relation = { tag = HAS value = 75 }
		relation = { tag = OYO value = 75 }
		relation = { tag = MAL value = -100 }
		relation = { tag = MOR value = -100 }
	}
	knownprovinces = {
		733 735 736 805 806 1487 1488 1489 1490 1491 1492 1493 1494 1495 1496 1497 1498 1499 1500 1501 1595 1596 1597
	}
	ownedprovinces = {
		1596 1597
	}
	controlledprovinces = {
		1596 1597
	}
	nationalprovinces = {
		1596 1597
	}
	claimedprovinces = {
		1487 1495 1595
	}

	city = {
		population = 1200
		location = 1596
	}
	city = {
		fortress = { level = 1 }
		population = 3500
		location = 1597
		capital = yes
	}

	landunit = { 
		id = { type = 6001 id = 751 } 
		name = "Tuareg Tribesmen"
		location = 1597
		infantry = 1500
		cavalry = 4000
		artillery = 0 
	} 

	technology = {
		stability = { level = 1 value = 0 }
		infra = { level = 0 value = 0 }
		trade = { level = 1 value = 0 }
		land = { level = 0 value = 0 }
		naval = { level = 0 value = 0 }
	}
}
