#Yemen/Aden#

country = { 
    tag = ADE 
    ai = "ADE_1399.txt"
    colonialattempts = 0 
    colonialnation = no 
    major = no 
    colonists = 0 
    cancelledloans = 0 
    extendedloans = 0 
    treasury = 99 
    inflation = 0 
    merchants = 0.083333 
    religion = { type = sunni }
    culture = { type = arabic }
    diplomacy = { 
    } 
    knownprovinces = { 
                      357 358 359 360 441 470 471 472 473 474 475 476 477 478 479 480 
                      481 482 483 484 485 486 487 488 489 490 491 492 493 494 495 496 
                      497 498 499 500 501 502 503 504 505 506 507 508 509 525 526 527 
                      528 529 530 531 532 533 534 535 536 537 538 539 540 541 547 568 
                      741 742 743 744 745 746 747 748 749 750 751 752 753 754 755 756 
                      757 759 760 820 997 1002 1003 1004 1005 1006 1007 1008 1009 1010 
                      1011 1012 1059 1060 1061 1062 1063 1064 1065 1066 1067 1068 1069 
                      1070 1071 1134 1135 1136 1331 1359 1363 1525 1526 1529 1530 1592 
                      1609 1610 1611 1613 
                      }

    ownedprovinces = { 
        500 501 } 
    controlledprovinces = { 
        500 501 } 
    nationalprovinces = { 
        499 500 501 } 
    city = {
    	fortress = { level = 1 }   
        population = 2000
        location = 500 
       capital = yes 
        } 
    city = {
    	fortress = { level = 1 }   
        population = 1200
        location = 501 
        } 
    landunit = { 
        id = { type = 9423 id = 690 } 
        name = "Aden Army" 
        location = 500 
        infantry = 30000 
        cavalry = 10000 
        artillery = 0 
        } 
    navalunit = { 
        id = { type = 9423 id = 692 } 
        name = "Aden Fleet" 
        location = 500 
        warships = 5 
        galleys = 0 
        transports = 0 
        } 
    technology = {
		stability = { level = 2 value = 42 }
      	infra = { level = 1 value = 50 }
		trade = { level = 1 value = 50 }
      	land = { level = 1 value = 0 } 
      	naval = { level = 1 value = 0 } 
    } 
} 


