
#Mali#

country = { 
    tag = MAL 
    colonialattempts = 0 
    colonialnation = no 
    major = no 
    colonists = 0 
    cancelledloans = 0 
    extendedloans = 0 
    treasury = 200 
    inflation = 0 
    merchants = 0 
    religion = { type = sunni }
    culture = { type = mali }
    diplomacy = { 
		relation = { tag = SUS value = -100 }
        } 
    knownprovinces = { 
		791 792 793 794 795 1487 1488 1489 1490 1491 1492 1493 1494 1495 1496 1497 1498 1499 1500 1501 1502 } 
    ownedprovinces = { 
        1487 1488 1489 1491 1492 1495 } 
    controlledprovinces = { 
        1487 1488 1489 1491 1492 }
    nationalprovinces = { 
        1487 1488 1489 1491 1492 1495 } 
    city = {         fortress = { level = 1 }  
        population = 8000
        location = 1489 
        capital = yes
        } 
    city = {         fortress = { level = 1 }  
        population = 5000
        location = 1487
        } 
    city = {         fortress = { level = 1 }  
        population = 5000
        location = 1488
        } 
    city = {         fortress = { level = 1 }  
        population = 5000
        location = 1491
        } 
    city = {         fortress = { level = 1 }  
        population = 5000
        location = 1492
    }
    city = {         fortress = { level = 1 }  
        population = 10000
        location = 1495
    } 
    technology = {
		stability = { level = 0 value = 42 }
      	infra = { level = 0 value = 10 }
		trade = { level = 0 value = 70 }
      	land = { level = 0 value = 50 } 
      	naval = { level = 0 value = 0 } 
    } 
} 


