#White Horde#

country = { 
    tag = WHR 
    colonialattempts = 0 
    colonialnation = no 
    major = no 
    colonists = 0 
    cancelledloans = 0 
    extendedloans = 0 
    treasury = 100 
    inflation = 0 
    merchants = 0.083333 
    religion = { type = sunni }
    culture = { 
		type = altai
		type = mongol
		 }
    diplomacy = { 
    	relation = { tag = MOS value = 100 refusetrade = no }  
    	relation = { tag = RYA value = 100 refusetrade = no } 
    	relation = { tag = TVE value = 100 refusetrade = no } 
    	relation = { tag = TIM value = -200 refusetrade = no } 
    }
    knownprovinces = { 471
                      478 479 480 481 482 483 484 485 486 487 488 489 490 
                      491 492 493 494 495 496 497 498 510 511 512 513 514 
                      515 516 517 518 519 520 521 522 523 524 525 526 527 
                      528 529 530 531 532 533 534 535 578 579 742 744 745 
                      746 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 
			464 1013 1014 1015 1016 1017 1326 1327 1529 1530 1531 
			465 1532 1533 1534 1535 1536 1570 1571 1573 1592 1594 
			    1609 1610 1611 1613 448 272 271 270 279 461 462 295 450
			451 296 294 293 298 297 299 292 300 291 288 284 287 285 286 280 281 278 274 277
			316 325 317 324 477 476 475 474 473 472 470 469 318 319
    }
    ownedprovinces = { 
	513 514 515 517 519 520 516 518 1534 1535 1536 510 511 512 578 579 1570 1571 1573 }
    controlledprovinces = { 
	513 514 515 517 519 520 516 518 1534 1535 1536 510 511 512 578 579 1570 1571 1573 }
    nationalprovinces = { 
	513 514 515 517 519 520 516 518 1534 1535 1536 510 511 512 578 579 1570 1571 1573 }
    city = {
    	fortress = { level = 1 }  
        population = 1500
        location = 510 
    }
    city = {
    	fortress = { level = 1 }  
        population = 1400
        location = 511 
    }
    city = {
    	fortress = { level = 1 }  
        population = 1200
        location = 512 
    }
	city = {
		fortress = { level = 1 }
		population = 3000
		location = 517
	}
    city = {
    	fortress = { level = 1 }  
        population = 1200
        location = 578
    }
	city = {
		fortress = { level = 1 }
		population = 2000
		location = 579
	}
    city = {
    	fortress = { level = 1 }  
        population = 1200
        location = 1570
    }
    city = {
    	fortress = { level = 1 }  
        population = 1200
        location = 1571
    }
    city = {
    	name = "Sibir"
    	fortress = { level = 1 }  
        population = 3000
        location = 1573
    }    
    city = {         fortress = { level = 1 }  
        population = 7000
        location = 516 
        } 
    city = {
    	fortress = { level = 1 }
        population = 6000
        location = 518 
        }
    city = {         fortress = { level = 1 }  
        population = 6000
        location = 1534 
        capital = yes 
        } 
    city = {         fortress = { level = 1 }  
        population = 8000
        location = 1535 
        } 
    city = {         fortress = { level = 1 }  
        population = 4000
        location = 1536
        } 
    city = {
    	fortress = { level = 1 }
        population = 3000
        location = 513
    }
    city = {
    	fortress = { level = 1 }
        population = 3500
        location = 514
    }
    city = {
    	fortress = { level = 1 }
        population = 7000
        location = 515 
    } 
    city = {
    	fortress = { level = 1 }
        population = 8000
        location = 519 
        } 
    city = {
    	fortress = { level = 1 }
        population = 4000
        location = 520
        } 
	landunit = { 
        id = { type = 6001 id = 213 } 
        name = "Nogay Horde"
        location = 519
        infantry = 0
        cavalry = 10000 
        artillery = 0 
      } 
	landunit = { 
        id = { type = 6001 id = 214 } 
        name = "White Horde"
        location = 1534
        infantry = 0
        cavalry = 15000 
        artillery = 0 
    } 

    technology = {
		stability = { level = 0 value = 42 }
        infra = { level = 0 value = 20 }
	  	trade = { level = 0 value = 20 }
        land = { level = 0 value = 50 } 
        naval = { level = 0 value = 0 } 
    } 
} 

