# cree

country = { 
    tag = CEE 
    colonialattempts = 0 
    colonialnation = no 
    major = no 
    colonists = 0 
    cancelledloans = 0 
    extendedloans = 0 
    treasury = 99 
    inflation = 0 
    merchants = 0.083333 
    religion = { type = pagan }
    culture = { type = cree }
    diplomacy = {
    	relation = { tag = OJI value = 100 } 
        } 
    knownprovinces = { 
	74 75 59 77 78 79 80 93 72 81 82 71 83 91 92 97 98 107 89 90 100 99 106 94 95 96 133 134 136 135 132 131 127 128 129 130 1369 1370 1371 1372 }
    ownedprovinces = { 
        133 134 135 136 131 132 } 
    controlledprovinces = { 
        133 134 135 136 131 132 } 
    nationalprovinces = { 
        133 134 135 136 131 132 } 
    city = {         fortress = { level = 1 }  
        population = 2000
        location = 133 
        capital = yes 
        } 
    city = {
        population = 1000
        location = 134 
        } 
    city = {
        population = 1000
        location = 135 
        }
    city = {
        population = 1000
        location = 136 
        }
    city = {
        population = 1000
        location = 131 
        }
    city = {
        population = 1000
        location = 132 
        } 
    technology = {
		stability = { level = 2 value = 42 }
        infra = { level = 0 value = 20 }
	  	trade = { level = 0 value = 20 }
        land = { level = 0 value = 0 } 
        naval = { level = 0 value = 0 } 
    } 
} 

