# Chagatai Khanate #

country = { 
    tag = CHG
    colonialattempts = 0 
    colonialnation = no 
    major = no 
    colonists = 0 
    cancelledloans = 0 
    extendedloans = 0 
    treasury = 150 
    inflation = 0.100000 
    merchants = 0.083333 
    religion = { type = sunni }
    culture = { type = uighur }
    diplomacy = {
		relation = { tag = NYN value = -25 } 
    } 
    knownprovinces = { 
    	272 296 446 447 448 449 451 452 453 454 455 456 457 458 459 460 461 462 463 466 467 468 510 511 512 513 514 515 516 517 518 519 520 521 522 523 524 525 526 533 649 653 1527 1528 1531 1532 1533 1534 1535 1536 1539 1540 1541 1542 1543 1544 1559 1591 1592 1593 1594 1598 1599 1600 1601 1602 1603 1604 1605 1606 1607 1608
    } 
    ownedprovinces = { 
        521 522 523 524 1532 1533 1599 1600 1601 1602 1603 1604 1605 1606 1607 1608 }
    controlledprovinces = { 
        521 522 523 524 1532 1533 1599 1600 1601 1602 1603 1604 1605 1606 1607 1608 } 
    nationalprovinces = { 
        #1598 - figure out how they get this core
	1599 1600 1601 1602 1603 1604 1605 1606 1607 1608 } 
    city = {
        population = 4000
        location = 1600
    }
    city = {
    	fortress = { level = 1 }
        population = 7000
        location = 1601
        capital = yes
    }
    city = {
        population = 5000
        location = 1602 
    }
    city = {
        population = 5000
        location = 1603
    }
    city = {         
        population = 5000
        location = 1604
    } 
    city = {
        population = 4000
        location = 1605
    }
    city = {
        population = 4000
        location = 1606
    }
    city = {
        population = 4000
        location = 1607
    } 
    city = {
        population = 4000
        location = 1608
    } 
    city = {
    	fortress = { level = 1 }
        population = 6000
        location = 521 
        } 
    city = {
    	fortress = { level = 1 }
        population = 5000
        location = 522 
        }
    city = {
    	fortress = { level = 1 }
        population = 7000
        location = 523 
        } 
    city = {
    	fortress = { level = 1 }
        population = 3000
        location = 524
        } 
    city = {
        population = 900
        location = 1532 
    } 
    city = {
    	fortress = { level = 1 }
        population = 6500
        location = 1533 
        } 
    city = {         
        population = 2800
        location = 1599
    }
	landunit = { 
        id = { type = 6001 id = 230 }
        name = "Chagatai Horde"
        location = 1601
        infantry = 0
        cavalry = 20000
        artillery = 0
    }
    technology = {
		stability = { level = 2 value = 42 }
        infra = { level = 0 value = 0 }
	  	trade = { level = 0 value = 0 }
        land = { level = 0 value = 0 } 
        naval = { level = 0 value = 0 }
        group = muslim
    } 
}