# Zapotek Empire #

country = { 
    tag = ZAP 
    ai = "peaceful.ai"
    colonialattempts = 0 
    colonialnation = no 
    major = no 
    colonists = 0 
    cancelledloans = 0 
    extendedloans = 0 
    treasury = 120 
    inflation = 0 
    merchants = 0.083333 
    religion = { type = pagan }
    culture = { type = zapotek }
    diplomacy = { 
    } 
    knownprovinces = { 
        14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 822 1477 1478 1479 } 
    ownedprovinces = { 
        30 31 } 
    controlledprovinces = { 
        30 31 } 
    nationalprovinces = { 
        30 31 } 
    city = {
    	fortress = { level = 1 }
        population = 5000
        location = 30 
        capital = yes 
    } 
    city = {
        population = 5000
        location = 31 
    }
    technology = {
		stability = { level = 2 value = 42 }
        infra = { level = 1 value = 0 }
	  	trade = { level = 1 value = 0 }
        land = { level = 0 value = 0 } 
        naval = { level = 0 value = 0 } 
    } 
} 

