# alnanbal

country = { 
    tag = ALN 
    colonialattempts = 0 
    colonialnation = no 
    major = no 
    colonists = 0 
    cancelledloans = 0 
    extendedloans = 0 
    treasury = 99 
    inflation = 0 
    merchants = 0.083333 
    religion = { type = thunderbird }
    culture = { type = abenaki }
    diplomacy = { 
        } 
    knownprovinces = { 
	66 67 69 70 71 72 81 82 83 84 85 86 87 88 89 90 91 92 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 1369 1370 1371 1372 }
    ownedprovinces = { 
        101 105 } 
    controlledprovinces = { 
        101 105 } 
    nationalprovinces = { 
        101 105 } 
    city = {         fortress = { level = 1 }  
        population = 2000
        location = 105 
        capital = yes 
        } 
    city = {
        population = 1000
        location = 101 
        } 
    technology = {
		stability = { level = 2 value = 42 }
        infra = { level = 0 value = 20 }
	  	trade = { level = 0 value = 20 }
        land = { level = 0 value = 0 } 
        naval = { level = 0 value = 0 } 
    } 
} 

