#potawatomi

country = { 
    tag = POT 
    colonialattempts = 0 
    colonialnation = no 
    major = no 
    colonists = 0 
    cancelledloans = 0 
    extendedloans = 0 
    treasury = 99 
    inflation = 0 
    merchants = 0.083333 
    religion = { type = thunderbird }
    culture = { type = shawnee }
    diplomacy = {
     }
    knownprovinces = { 
	56 59 60 65 66 67 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 90 91 92 93 94 95 96 97 98 99 100 107 1369 1370 1371 1372 }
    ownedprovinces = { 
        81 82 } 
    controlledprovinces = { 
        81 82 } 
    nationalprovinces = { 
        81 82 } 
    city = {         fortress = { level = 1 }  
        population = 1000
        location = 81 
        capital = yes 
        } 
    city = {
        population = 1000
        location = 82 
        } 
    technology = {
		stability = { level = 2 value = 42 }
        infra = { level = 0 value = 20 }
	  	trade = { level = 0 value = 20 }
        land = { level = 0 value = 0 } 
        naval = { level = 0 value = 0 } 
    } 
} 