# Huron #

country = { 
    tag = HUR 
    colonialattempts = 0 
    colonialnation = no 
    major = no 
    colonists = 0 
    cancelledloans = 0 
    extendedloans = 0 
    treasury = 99 
    inflation = 0 
    merchants = 0.083333 
    religion = { type = thunderbird }
    culture = { type = iroquis }
    diplomacy = { 
        } 
    knownprovinces = { 
	66 67 69 70 71 72 81 82 83 84 85 86 87 88 89 90 91 92 95 96 97 98 99 100 105 106 107 108 109 110 111 1369 1370 1371 1372 }
    ownedprovinces = { 
        97 98 106 } 
    controlledprovinces = { 
        97 98 106 } 
    nationalprovinces = { 
        97 98 106 } 
    city = {         fortress = { level = 1 }  
        population = 2000
        location = 98 
        capital = yes 
        } 
    city = {
        population = 1000
        location = 97 
        } 
    city = {
        population = 1000
        location = 106 
        } 
    technology = {
		stability = { level = 2 value = 42 }
        infra = { level = 0 value = 20 }
	  	trade = { level = 0 value = 20 }
        land = { level = 0 value = 0 } 
        naval = { level = 0 value = 0 } 
    } 
} 

