# Cambodia #

country = { 
    tag = KHM 
    colonialattempts = 0 
    colonialnation = no 
    major = no 
    colonists = 0 
    cancelledloans = 0 
    extendedloans = 0 
    treasury = 200 
    inflation = 0 
    merchants = 0 
    religion = { type = buddhism }
    culture = { 
    	type = khmer
    }
    diplomacy = { 
    } 
    knownprovinces = { 
                               556 557 558 641 642 649 650 652 653 654 655 656 657 658 659 660 
                               661 662 663 664 665 666 667 668 669 670 671 672 673 674 675 676 
                               677 678 679 680 685 686 687 688 940 941 942 944 1018 1019 1020 
                               1021 1078 1079 1080 1081 1082 1083 1084 1085 1143 1144 1145 
                               1146 1147 1149 1351 1356 1357 1358 1544 1545 1546 1547 1548 
                               1549 1550 1551 1552 1553 1554 1555 1556 
	}
    ownedprovinces = { 
        666 667 668 } 
    controlledprovinces = { 
        666 667 668 } 
    nationalprovinces = { 
        666 667 668 } 
    city = {         fortress = { level = 1 }  
        population = 8000
        location = 668 
        capital = yes
        } 
    city = {         fortress = { level = 1 }  
        population = 8000
        location = 667 
        } 
    city = {         fortress = { level = 1 }  
        population = 8000
        location = 666
        } 
    landunit = { 
        id = { type = 9423 id = 829 } 
        name = "Khmer Army"
        location = 668
        infantry = 20000
        cavalry = 5000
        artillery = 0 
    } 
    technology = {
      	stability = { level = -1 value = 0 }
      	infra = { level = 0 value = 10 }
      	trade = { level = 0 value = 70 }
      	land = { level = 0 value = 50 } 
      	naval = { level = 0 value = 0 } 
    } 
} 


