#ojibwa

country = { 
    tag = OJI 
    colonialattempts = 0 
    colonialnation = no 
    major = no 
    colonists = 0 
    cancelledloans = 0 
    extendedloans = 0 
    treasury = 99 
    inflation = 0 
    merchants = 0.083333 
    religion = { type = thunderbird }
    culture = { type = huron }
    diplomacy = {
    	relation = { tag = CEE value = 100 }	 
    }
    knownprovinces = { 
	74 75 59 77 78 79 80 93 72 81 82 71 83 91 92 97 98 107 89 90 100 99 106 94 95 96 133 134 136 135 132 131 127 128 129 130 1369 1370 1371 1372 }
    ownedprovinces = { 
        93 94 95 96 } 
    controlledprovinces = { 
        93 94 95 96 } 
    nationalprovinces = { 
        93 94 95 96 } 
    city = {         fortress = { level = 1 }  
        population = 1000
        location = 95 
        capital = yes 
        } 
    city = {
        population = 1000
        location = 94 
        }
    city = {
        population = 1000
        location = 93 
        } 
    city = {
        population = 1000
        location = 96 
        } 
    technology = {
		stability = { level = 2 value = 42 }
        infra = { level = 0 value = 20 }
	  	trade = { level = 0 value = 20 }
        land = { level = 0 value = 0 } 
        naval = { level = 0 value = 0 } 
    } 
} 