# Hokucho #

country = { 
    tag = HOK 
    colonialattempts = 0 
    colonialnation = no 
    major = no 
    colonists = 0 
    cancelledloans = 0 
    extendedloans = 0 
    treasury = 300 
    inflation = 0 
    merchants = 0.083333 
    religion = { type = shinto }
    culture = { type = japanese }
    diplomacy = { 
    }
    knownprovinces = { 
        625 626 638 639 640 641 642 643 645 646 647 648 649 650 651 652 653 654 655 656 657 658 659 660 661 683 684 685 686 687 688 689 886 940 941 942 943 944 945 946 947 948 949 1018 1019 1020 1021 1085 1087 1088 } 
    ownedprovinces = { 
        684 686 687 } 
    controlledprovinces = { 
        684 686 687 } 
    nationalprovinces = { 
        683 684 685 686 687 688 } 
    city = {
    	fortress = { level = 1 }  
        population = 35000
        location = 684 
    } 
    city = {
    	fortress = { level = 1 }  
        population = 60000
        location = 686 
        capital = yes 
    } 
    city = {
    	fortress = { level = 1 }  
        population = 35000
        location = 687 
    } 
    landunit = { 
        id = { type = 9423 id = 2005 } 
        name = "Imperial Army" 
        location = 686 
        infantry = 20000
        cavalry = 5000
        artillery = 0 
    } 
    navalunit = { 
        id = { type = 9423 id = 845 } 
        name = "Imperial Fleet" 
        location = 686
        warships = 0
        galleys = 15
        transports = 16 
    } 
    technology = {
		stability = { level = 2 value = 42 }
        infra = { level = 1 value = 0 }
	  	trade = { level = 1 value = 0 }
        land = { level = 1 value = 100 } 
        naval = { level = 1 value = 0 } 
    } 
} 

